# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  orderapi:
    image: orderapi
    build:
      context: .
      dockerfile: src/Order.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
